### ISSUE TITLE
Gravity Forms Currency Fields not Mapping Properly to Currency Fields in Pods

### ISSUE THREAD

**Issue by jimtrue** [pods-framework/pods-gravity-forms#34]
All Currency field are coming across as 0,00 when mapped as Euro, but the Total Calculated field is coming across correctly. I'm getting JSON export from Gravity Forms and JSON Migrate Package from Pods so we can match user's configuration. Brought to Slack after posting on Forum Post:
http://pods.io/forums/topic/gravity-form-price-field-issue/

**Comment by jimtrue** [comment]
Included are Gravity Forms Configuration and Pods Configuration

[issue-34-gravity-forms-pods-configuration.zip](https://github.com/pods-framework/pods-gravity-forms/files/89206/issue-34-gravity-forms-pods-configuration.zip)

**Comment by jimtrue** [comment]
<img width="973" alt="screen_shot_2016-01-13_at_18 30 36" src="https://cloud.githubusercontent.com/assets/3052875/12302194/fbc157a8-b9f1-11e5-96c1-278dbaa4f16e.png">

Pods Feed Configuration, Gravity Forms Settings needs to be set at Current Euro

**Comment by gnappo74** [comment]
Hi i have tried more and there is also another issue when u use product field with price inserted by the user, gravity form give an error said: "name of the field" is not a number, i have deleted the fields connected to pods that receive teh data from product price entered by user and now GF back to work, still remain the issue of value passed from GF to pods is still 0,00 but total field works.

**Comment by jimtrue** [comment]
'name of the field is not a number' would be a Gravity Form specific error, not Pods.

The primary issue I'm seeing is that the Euro values keep flipping back and forth with your conditionals and they're definitely not passing over. Let's try to keep this particular issue restricted to ONLY the Euro Currency Values not passing to Pods, okay?

**Comment by gnappo74** [comment]
yes of course Jim, the main issue is that surely, but quite strange that if i deactive from GF pods setting the pods connected the error is not a number disappear i have create a localhost installation with GF clean and no error, so i think that is always connected to pass the data to pods, and when there is this particular situation with price inserted by user --> error.

**Comment by jimtrue** [comment]
Sorry @gnappo74 that above paragraph is unclear to me. When you deactivate the GF to Pods plugin, you don't receive the errors on your form? Form entry doesn't connect to the Pods processor, only when you hit submit and you're writing the final data to Pods entries. If they don't match field types, you're going to get an error. Currency is not a Number, it's a Currency object (and the input has to match the style you've defined).

**Comment by gnappo74** [comment]
ok Jim recap from yesterday: issue of pass the data with currency from GF product field with Euro still remain and as you know instead the GF field "total" works.
In the pods settings inside gravity form when you map the data to GF field you see in my example staffe (pods fields) and totale staffe € GF field; the totale staffe GF field is always a product field which price is not given like for example "router access point field", but it will be inserted by the user
So when you fill all the form the field with price inserted by the users give the error during the submission for example " staffe is not a number"; so if you go back in pods setting inside GF and unlink this field not mapping them the error disappear.
The field type are always mapping to currency because are currencies both like total, or other.

**Comment by gnappo74** [comment]
any news?

**Comment by sc0ttkclark** [comment]
Looking at this issue for this week too

**Comment by gnappo74** [comment]
great, very curious

**Comment by sc0ttkclark** [comment]
Issue is fixed through https://github.com/pods-framework/pods/pull/3436
