### ISSUE TITLE
Gravity Forms Pods addon not supplying values correctly causing Gravity Forms validation to fail. 

### ISSUE THREAD

**Issue by httpmax** [pods-framework/pods-gravity-forms#95]
[test-gravityforms-export-2018-01-09.json.txt](https://github.com/pods-framework/pods-gravity-forms/files/1616367/test-gravityforms-export-2018-01-09.json.txt)
[pods-type-and-taxon.txt](https://github.com/pods-framework/pods-gravity-forms/files/1616368/pods-type-and-taxon.txt)

Above are the exports of Gravity forms and the pod with content type and taxonomy. 

I am using the gravity forms addon to map the pod to the form and i am populating the forms content from the pod.

In my form I have 3 checkboxes which are populated via the pod. Neither the pod or the gravity forms is marked as required. Yet when I make a selection and submit the form, gravity forms claims nothing was selected.  After testing a bit I noticed that only if the first checkbox is selected will it submit the form. But if the first one is not selected while the other are selected, it will claim the values are empty and wont let me proceed. 

Hoping you guys can help me out and resolve this. 

Many thanks.

**Comment by jimtrue** [comment]
@httpmax Unfortunately the Feed configuration isn't included in the Gravity Forms export. Can you provide a screenshot of your Pods Feed configuration for this form?

**Comment by httpmax** [comment]
The Pod: https://i.imgur.com/cx8R6qo.png

**Comment by jimtrue** [comment]
Thank you for that @httpmax but we need the Gravity Form, Pods Feed configuration screen (where you map the fields in your Pod to the fields in your form). The pods configuration is loaded in your JSON above.

**Comment by httpmax** [comment]
My apologies

https://i.imgur.com/8WFBOux.png

**Comment by jimtrue** [comment]
@httpmax I think this has more to do with your structure than anything else. You've got a Taxonomy with a relationship field to itself and you're attempting to create a form that populates that relationship 'choice' when you don't even have a 'term' defined in your form. You can't do that. You have to define a taxonomy term for a form, or you can't save any custom term meta for a non-existent form which is what your form is attempting to do.

What are you actually trying to accomplish with this structure and form. You don't provide enough details with your structure or configuration of your taxonomy and post type in order to determine what you're trying to do. What is the XY? http://meta.stackoverflow.com/questions/66377/what-is-the-xy-problem

**Comment by sc0ttkclark** [comment]
Please try the latest Pods GF 1.4 beta https://github.com/pods-framework/pods-gravity-forms/archive/1.4-beta.zip

**Comment by sc0ttkclark** [comment]
Fixed in #86 (ZIP: https://github.com/pods-framework/pods-gravity-forms/archive/feature/skc-fixes.zip)
